{
	"version": 1748260419,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/sprite30-sheet0.png",
		"images/sprite30-sheet1.png",
		"images/slimered-sheet0.png",
		"images/slimered-sheet1.png",
		"images/bomtawon-sheet0.png",
		"images/tawonbomb-sheet0.png",
		"images/tawonbomb-sheet1.png",
		"images/tawonbomb-sheet2.png",
		"images/ulat-sheet0.png",
		"images/boss-sheet0.png",
		"images/boss-sheet1.png",
		"images/flyingdemon-sheet0.png",
		"images/fire1-sheet0.png",
		"images/fire1-sheet1.png",
		"images/fire1-sheet2.png",
		"images/sprite3-sheet0.png",
		"images/fireboss-sheet0.png",
		"images/fireboss-sheet1.png",
		"images/reiko-sheet0.png",
		"images/reiko-sheet1.png",
		"images/reiko-sheet2.png",
		"images/sprite2-sheet0.png",
		"images/platform.png",
		"images/platform2.png",
		"images/platform3.png",
		"images/platform4.png",
		"images/background2.png",
		"images/backgroundpngtutorial-sheet0.png",
		"images/props.png",
		"images/cursor-sheet0.png",
		"images/hitbox-sheet0.png",
		"images/nextlayout-sheet0.png",
		"images/offscrollto-sheet0.png",
		"images/boss_hitbox-sheet0.png",
		"images/tp-sheet0.png",
		"images/tp2-sheet0.png",
		"images/camera-sheet0.png",
		"images/fadein-sheet0.png",
		"images/salahjalan-sheet0.png",
		"images/backgroundtext-sheet0.png",
		"images/reikovn-sheet0.png",
		"images/latarresto-sheet0.png",
		"images/visualnoveltriger-sheet0.png",
		"images/portal-sheet0.png",
		"images/portal-sheet1.png",
		"images/portal-sheet2.png",
		"images/skipbutton-sheet0.png",
		"images/spritefont.png",
		"images/pause-sheet0.png",
		"images/pausebackground-sheet0.png",
		"images/startpause-sheet0.png",
		"images/settingpause-sheet0.png",
		"images/quitpause-sheet0.png",
		"images/borderboss-sheet0.png",
		"images/bosshealth-sheet0.png",
		"images/bordercharacter-sheet0.png",
		"images/charhud-sheet0.png",
		"images/borderraiko-sheet0.png",
		"images/space-sheet0.png",
		"images/borderitems-sheet0.png",
		"images/baskethud-sheet0.png",
		"images/inforevive.png",
		"images/sprite38-sheet0.png",
		"images/itemhealth-sheet0.png",
		"images/itemrespawn-sheet0.png",
		"images/kanan-sheet0.png",
		"images/kiri-sheet0.png",
		"images/zbutton-sheet0.png",
		"images/sprite22-sheet0.png",
		"images/kiriandro-sheet0.png",
		"images/zandro-sheet0.png",
		"images/atasandro-sheet0.png",
		"images/kananandro-sheet0.png",
		"images/tilemap.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite10-sheet0.png",
		"images/sprite11-sheet0.png",
		"images/sprite12-sheet0.png",
		"images/sprite13-sheet0.png",
		"images/playbutton-sheet0.png",
		"images/settings-sheet0.png",
		"images/sprite16-sheet0.png",
		"images/exit-sheet0.png",
		"images/sprite18-sheet0.png",
		"images/sprite19-sheet0.png",
		"images/sprite21-sheet0.png",
		"images/b0432acbb3695557f9d89666e0cb-sheet0.png",
		"images/imageremovebgpreview-sheet0.png",
		"images/particles.png",
		"images/sprite28-sheet0.png",
		"images/sprite28-sheet1.png",
		"images/sprite15-sheet0.png",
		"images/sprite15-sheet1.png",
		"images/sprite17-sheet0.png",
		"images/sprite17-sheet1.png",
		"images/revivepoint-sheet0.png",
		"images/revivebar-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sprite27-sheet0.png",
		"images/sprite27-sheet1.png",
		"images/sprite27-sheet2.png",
		"images/sprite29-sheet0.png",
		"images/sprite29-sheet1.png",
		"images/sprite29-sheet2.png",
		"images/loader-sheet0.png",
		"images/sprite25-sheet0.png",
		"images/sprite31-sheet0.png",
		"images/sprite32-sheet0.png",
		"images/buttongameover-sheet0.png",
		"images/sprite34-sheet0.png",
		"images/sprite35-sheet0.png",
		"images/sprite36-sheet0.png",
		"images/sprite37-sheet0.png",
		"images/sprite40-sheet0.png",
		"images/sprite41-sheet0.png",
		"images/sprite42-sheet0.png",
		"images/sprite43-sheet0.png",
		"images/sprite44-sheet0.png",
		"images/sprite45-sheet0.png",
		"media/buku open.m4a",
		"media/buku open.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/collect.m4a",
		"media/collect.ogg",
		"media/hehh.m4a",
		"media/hehh.ogg",
		"media/kena hit.m4a",
		"media/kena hit.ogg",
		"media/load.m4a",
		"media/load.ogg",
		"media/mati.m4a",
		"media/mati.ogg",
		"media/pause.m4a",
		"media/pause.ogg",
		"media/pedang kena.m4a",
		"media/pedang kena.ogg",
		"media/quest notiv.m4a",
		"media/quest notiv.ogg",
		"media/serang.m4a",
		"media/serang.ogg",
		"media/tele.m4a",
		"media/tele.ogg",
		"media/void.m4a",
		"media/void.ogg",
		"media/yt1s mision.m4a",
		"media/yt1s mision.ogg",
		"media/yt1s save.m4a",
		"media/yt1s save.ogg",
		"media/yt1s start.m4a",
		"media/yt1s start.ogg",
		"media/all stage.m4a",
		"media/all stage.ogg",
		"media/boss fix.m4a",
		"media/boss fix.ogg",
		"media/opening aslii.m4a",
		"media/opening aslii.ogg",
		"media/serang kena.m4a",
		"media/serang kena.ogg",
		"media/serang tidak kena.m4a",
		"media/serang tidak kena.ogg",
		"media/visual novel.m4a",
		"media/visual novel.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}